vanpine:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: vanpine
    username: root
    password: wangbing201708
    redisHost: 192.168.61.135
    redisPort: 6379